site_name: lrcparser
repo_url: https://github.com/283375/lrcparser_python

nav:
    - lrcparser: index.md
    - Usage: usage.md
    - API:
        - LrcTime: api/time.md
        - LrcParser: api/parser.md

theme:
    name: null
    custom_dir: 'docs/.theme/'
    static_templates:
        - 404.html

watch:
    - docs/.theme/

markdown_extensions:
    - admonition
    - toc:
        baselevel: 1
        permalink: '#'
        slugify: !!python/name:markdown.extensions.toc.slugify_unicode

plugins:
    - i18n:
        default_language: zh_CN
        # default_language_only: true
        docs_structure: folder
        material_alternate: false
        languages:
            en:
                name: English
                build: true
            zh_CN:
                name: 简体中文
                build: true
        nav_translations:
            zh_CN:
                Usage: 使用
